export const actionTypes = [
  {
    id: 'product_like',
    associated_collection: 'products',
    can_archive: false,
    community_admin_visible: false,
    description: 'product is liked',
    name: 'Product liked',
    user_visible: true,
  },
  {
    id: 'product_view',
    associated_collection: 'products',
    can_archive: true,
    community_admin_visible: false,
    description: 'product is viewed',
    name: 'Product viewed',
    user_visible: true,
  },
  {
    id: 'shop_view',
    associated_collection: 'shops',
    can_archive: true,
    community_admin_visible: false,
    description: 'shop is viewed',
    name: 'Shop viewed',
    user_visible: true,
  },
  {
    id: 'user_invite',
    associated_collection: 'invites',
    can_archive: false,
    community_admin_visible: true,
    description: 'invited a new user',
    name: 'User invite',
    user_visible: true,
  },
  {
    id: 'user_login',
    associated_collection: 'users',
    can_archive: false,
    community_admin_visible: false,
    description: 'user logged in',
    name: 'User login',
    user_visible: true,
  },
  {
    id: 'user_login_failed',
    associated_collection: 'users',
    can_archive: false,
    community_admin_visible: false,
    description: 'user failed login',
    name: 'User login failed',
    user_visible: true,
  },
  {
    id: 'user_logout',
    associated_collection: 'users',
    can_archive: false,
    community_admin_visible: false,
    description: 'user logged out',
    name: 'User logout',
    user_visible: true,
  },
]
