export const categories = [
  {
    id: 'dessert_pastries',
    archived: false,
    cover_url: '',
    description: 'sweets',
    icon_url: '',
    name: 'Desserts & Pastries',
    status: 'enabled',
  },
  {
    id: 'drinks',
    archived: false,
    cover_url: '',
    description: 'description of the drinks',
    icon_url: '',
    name: 'Drinks',
    status: 'enabled',
  },
  {
    id: 'fashion',
    archived: false,
    cover_url: '',
    description: 'clothes',
    icon_url: '',
    name: 'Fashion',
    status: 'enabled',
  },
  {
    id: 'food',
    archived: false,
    cover_url: '',
    description: 'food',
    icon_url: '',
    name: 'Food',
    status: 'enabled',
  },
  {
    id: 'home_goods',
    archived: false,
    cover_url: '',
    description: 'beds and things',
    icon_url: '',
    name: 'Home Goods',
    status: 'enabled',
  },
  {
    id: 'meals_snacks',
    archived: false,
    cover_url: '',
    description: 'lunch foods',
    icon_url: '',
    name: 'Meals & Snacks',
    status: 'enabled',
  },
]
