export const userFields = [
  '_meta',
  'address',
  'archived',
  'birthdate',
  'community_id',
  'created_at',
  'display_name',
  'email',
  'first_name',
  'last_name',
  'profile_photo',
  'registration',
  'roles',
  'status',
  'updated_at',
]

export const shopFields = [
  '_meta',
  'archived',
  'community_id',
  'cover_photo',
  'created_at',
  'description',
  'is_close',
  'name',
  'operating_hours',
  'payment_options',
  'profile_photo',
  'status',
  'user_id',
  'updated_at',
]

export const productFields = [
  '_meta',
  'archived',
  'availability',
  'base_price',
  'can_subscribe',
  'community_id',
  'created_at',
  'description',
  'gallery',
  'name',
  'product_category',
  'quantity',
  'shop_id',
  'status',
  'user_id',
  'updated_at',
]

export const chatFields = [
  'archived',
  'chat_type',
  'community_id',
  'created_at',
  'customer_name',
  'last_message',
  'members',
  'shop_id',
  'product_id',
  'title',
  'updated_at',
]

export const conversationFields = [
  'archived',
  'created_at',
  'media',
  'message',
  'sender_id',
  'sent_at',
  'reply_to',
  'updated_at',
  'community_id',
  'chat_id',
]

export const orderFields = [
  'buyer_id',
  'community_id',
  'created_at',
  'delivery_address',
  'delivery_date',
  'delivered_date',
  'delivery_option',
  'is_paid',
  'instruction',
  'payment_method',
  'product_ids',
  'products',
  'proof_of_payment',
  'seller_id',
  'shop_id',
  'shop',
  'status_code',
  'updated_at',
  'cancellation_reason',
  'decline_reason',
  'product_subscription_id',
  'product_subscription_date',
]

export const productSubscriptionPlanFields = [
  'archived',
  'buyer_id',
  'community_id',
  'created_at',
  'instruction',
  'payment_method',
  'plan',
  'product',
  'product_id',
  'quantity',
  'seller_id',
  'shop_id',
  'shop',
  'status',
  'updated_at',
]

export const activityFields = [
  '_meta',
  'archived',
  'archived_at',
  'community_id',
  'created_at',
  'images',
  'message',
  'status',
  'updated_at',
  'user_id',
]

export const commentFields = [
  'archived',
  'archived_at',
  'activity_id',
  'community_id',
  'created_at',
  'images',
  'message',
  'status',
  'updated_at',
  'user_id',
]

export const communityFields = [
  '_meta',
  'archived',
  'address',
  'admin',
  'cover_photo',
  'created_at',
  'name',
  'profile_photo',
  'updated_at',
]

export const reportFields = [
  'user_id',
  'reported_user_id',
  'description',
  'community_id',
  'activity_id',
  'shop_id',
  'product_id',
  'created_at',
  'updated_at',
  'reporter_email',
  'reported_email',
  'report_type',
]
