export const userFields = [
  '_meta',
  'address',
  'archived',
  'birthdate',
  'community_id',
  'created_at',
  'display_name',
  'email',
  'first_name',
  'last_name',
  'profile_photo',
  'registration',
  'roles',
  'status',
  'updated_at',
]

export const shopFields = [
  '_meta',
  'archived',
  'community_id',
  'cover_photo',
  'created_at',
  'description',
  'is_close',
  'name',
  'operating_hours',
  'payment_options',
  'profile_photo',
  'status',
  'user_id',
  'updated_at',
]

export const productFields = [
  '_meta',
  'archived',
  'availability',
  'base_price',
  'can_subscribe',
  'community_id',
  'created_at',
  'description',
  'gallery',
  'name',
  'product_category',
  'quantity',
  'shop_id',
  'status',
  'user_id',
  'updated_at',
]

export const chatFields = [
  'archived',
  'chat_type',
  'community_id',
  'created_at',
  'customer_name',
  'last_message',
  'members',
  'shop_id',
  'product_id',
  'title',
  'updated_at',
]

export const conversationFields = [
  'archived',
  'created_at',
  'media',
  'message',
  'sender_id',
  'sent_at',
  'reply_to',
  'updated_at',
  'community_id',
  'chat_id',
]
