export const userFields = [
  '_meta',
  'address',
  'archived',
  'birthdate',
  'community_id',
  'created_at',
  'display_name',
  'email',
  'first_name',
  'last_name',
  'profile_photo',
  'registration',
  'roles',
  'status',
  'updated_at',
]
